name: smart-distribution

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: smart_distribution
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
